apiVersion: "serving.kserve.io/v1beta1"
kind: "InferenceService"
metadata:
  name: "bike-lgbm"
  namespace: kserve-inference
spec:
  predictor:
    serviceAccountName: kserve-sa
    ### START CONF HERE
    model:
      modelFormat:
        name: mlflow
      protocolVersion: v2
      storageUri: "s3://mlflow/5/9629b9889cda4752bd9fbbd2b71321f7/artifacts/lgbm-bike"
    ### END CONF HERE
