#!/bin/bash

#SBATCH -M ukko              # cluster (you may also use --cluster=ukko2)
#SBATCH -e out_%j            # stderr
#SBATCH -o out_%j            # stdout
#SBATCH --mem-per-cpu=300    # memory
#SBATCH -t 00:01:00          # time needed dd-hh:mm:ss
#SBATCH -n 32                 # number of cores
#SBATCH -p short             # queue

module load gompi

echo -e "\n=== Run started $(date) on $HOSTNAME ===\n"
mpirun -np 32  ./prob4
echo -e "\n=== Run finished $(date) $HOSTNAME ===\n"
