

p1:
	g++ -g -o ex3_p1 ex3_p1.cpp
p3:
	gcc -O0 -o ex3_p3_0 ex3p3.c
	gcc -O1 -o ex3_p3_1 ex3p3.c
	gcc -O2 -o ex3_p3_2 ex3p3.c
	gcc -O3 -o ex3_p3_3 ex3p3.c
p4:
	g++ -o ex3_p4 ex3_p4.cc -lm
clean:
	rm -f ex3_p1 ex3_p3_0 ex3_p3_1 ex3_p3_2 ex3_p3_3 ex3_p4